### PR TITLE
Add 2016 General Election Results

### PR DESCRIPTION
**Pull request by kipkosek**
I made three CSV files — district-wide, ward, and precinct — with the 2016 general election results from the DC Board of Elections site.

### CODE REVIEW

**Comment by dwillis** [comment]
Many thanks, @kipkosek! Any chance you can clean things up a bit to remove trailing whitespace in those CSV files?

**Comment by kipkosek** [comment]
Sure, I'll see what I can do.

**Comment by kipkosek** [comment]
Okay, I think this looks better. Let me know if anything else needs to be fixed.

**Comment by dwillis** [comment]
Looks great, thanks!

**Pull request merged**
